db_auth:
  user: ukrik
  name: auth
  port: 5432
  host: db
  password: secret
jaeger:
  host: jaeger # JAEGER_HOST
  port: 4317 # JAEGER_HOST
otlpmeter:
  host: alloy # OTLPMETER_HOST
  port: 4317 # OTLPMETER_HOST