app_name: my_service # APPNAME
app_ver: 0.0.1 # APPVER

jaeger:
  host: 0.0.0.0 # JAEGER_HOST
  port: 4317 # JAEGER_HOST

listen:
  host: 0.0.0.0 # LISTEN_HOST
  port: 11000 # LISTEN_PORT

log:
  level: "debug"

