

apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "trace_id=([a-f0-9]{32})"
          name: TraceID
          url: '$${__value.raw}'

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true